import {
  ActivityItem,
  AnnouncementItem,
  AssignmentItem,
  ClassItem,
  StudentItem,
} from "./types";

export const faculty = {
  name: "Dr. Ananya Rao",
  title: "Associate Professor, Computer Science",
  avatar: "https://i.pravatar.cc/150?img=47",
  email: "ananya.rao@faculty.edu",
};

export const classes: ClassItem[] = [
  {
    id: "cs301",
    name: "Data Structures & Algorithms",
    department: "Computer Science",
    semester: "Semester 3",
    studentCount: 64,
    banner: "from-blue-500 via-blue-600 to-indigo-700",
    code: "CS301",
    schedule: "Mon, Wed · 10:00 AM",
    room: "Room 214",
  },
  {
    id: "cs404",
    name: "Machine Learning Fundamentals",
    department: "Computer Science",
    semester: "Semester 7",
    studentCount: 48,
    banner: "from-purple-500 via-fuchsia-600 to-pink-600",
    code: "CS404",
    schedule: "Tue, Thu · 1:00 PM",
    room: "Lab 3",
  },
  {
    id: "cs210",
    name: "Database Management Systems",
    department: "Computer Science",
    semester: "Semester 4",
    studentCount: 71,
    banner: "from-emerald-500 via-teal-600 to-cyan-700",
    code: "CS210",
    schedule: "Mon, Fri · 9:00 AM",
    room: "Room 108",
  },
  {
    id: "cs512",
    name: "Cloud Computing & DevOps",
    department: "Computer Science",
    semester: "Semester 8",
    studentCount: 39,
    banner: "from-orange-500 via-amber-500 to-yellow-500",
    code: "CS512",
    schedule: "Wed, Fri · 3:00 PM",
    room: "Room 301",
  },
  {
    id: "cs150",
    name: "Discrete Mathematics",
    department: "Computer Science",
    semester: "Semester 2",
    studentCount: 82,
    banner: "from-rose-500 via-red-500 to-orange-600",
    code: "CS150",
    schedule: "Tue, Thu · 11:00 AM",
    room: "Room 220",
  },
  {
    id: "cs620",
    name: "Human-Computer Interaction",
    department: "Computer Science",
    semester: "Semester 6",
    studentCount: 28,
    banner: "from-sky-500 via-cyan-500 to-blue-600",
    code: "CS620",
    schedule: "Mon, Wed · 2:00 PM",
    room: "Studio 2",
  },
];

export const recentActivity: ActivityItem[] = [
  {
    id: "a1",
    type: "submission",
    title: "New submission received",
    description: "Rahul Mehta submitted 'Binary Search Trees — Lab 4'",
    time: "8 min ago",
    actor: "Rahul Mehta",
    avatar: "https://i.pravatar.cc/100?img=12",
  },
  {
    id: "a2",
    type: "ai",
    title: "AI grading completed",
    description: "42 submissions auto-graded for CS404 Quiz 2",
    time: "34 min ago",
    actor: "AI Assistant",
    avatar: "ai",
  },
  {
    id: "a3",
    type: "grade",
    title: "Marks published",
    description: "Mid-semester marks published for CS210",
    time: "1 hr ago",
    actor: "You",
    avatar: "https://i.pravatar.cc/150?img=47",
  },
  {
    id: "a4",
    type: "assignment",
    title: "Assignment created",
    description: "'Neural Network Basics — Assignment 3' posted to CS404",
    time: "2 hr ago",
    actor: "You",
    avatar: "https://i.pravatar.cc/150?img=47",
  },
  {
    id: "a5",
    type: "announcement",
    title: "New announcement",
    description: "Reminder posted about upcoming DBMS practical exam",
    time: "5 hr ago",
    actor: "You",
    avatar: "https://i.pravatar.cc/150?img=47",
  },
];

export const students: StudentItem[] = [
  {
    id: "s1",
    name: "Rahul Mehta",
    rollNumber: "CS301-014",
    email: "rahul.mehta@student.edu",
    avatar: "https://i.pravatar.cc/100?img=12",
    attendance: 92,
    average: 88,
    risk: "low",
  },
  {
    id: "s2",
    name: "Priya Sharma",
    rollNumber: "CS301-015",
    email: "priya.sharma@student.edu",
    avatar: "https://i.pravatar.cc/100?img=25",
    attendance: 96,
    average: 94,
    risk: "low",
  },
  {
    id: "s3",
    name: "Arjun Verma",
    rollNumber: "CS301-016",
    email: "arjun.verma@student.edu",
    avatar: "https://i.pravatar.cc/100?img=33",
    attendance: 64,
    average: 51,
    risk: "high",
  },
  {
    id: "s4",
    name: "Sneha Iyer",
    rollNumber: "CS301-017",
    email: "sneha.iyer@student.edu",
    avatar: "https://i.pravatar.cc/100?img=45",
    attendance: 81,
    average: 73,
    risk: "medium",
  },
  {
    id: "s5",
    name: "Karan Malhotra",
    rollNumber: "CS301-018",
    email: "karan.malhotra@student.edu",
    avatar: "https://i.pravatar.cc/100?img=52",
    attendance: 89,
    average: 79,
    risk: "low",
  },
  {
    id: "s6",
    name: "Neha Kapoor",
    rollNumber: "CS301-019",
    email: "neha.kapoor@student.edu",
    avatar: "https://i.pravatar.cc/100?img=29",
    attendance: 58,
    average: 47,
    risk: "high",
  },
  {
    id: "s7",
    name: "Aditya Nair",
    rollNumber: "CS301-020",
    email: "aditya.nair@student.edu",
    avatar: "https://i.pravatar.cc/100?img=60",
    attendance: 87,
    average: 82,
    risk: "medium",
  },
  {
    id: "s8",
    name: "Ishita Bose",
    rollNumber: "CS301-021",
    email: "ishita.bose@student.edu",
    avatar: "https://i.pravatar.cc/100?img=48",
    attendance: 98,
    average: 96,
    risk: "low",
  },
];

export const assignments: AssignmentItem[] = [
  {
    id: "as1",
    title: "Binary Search Trees — Lab 4",
    type: "assignment",
    dueDate: "Aug 5, 2026",
    points: 20,
    submitted: 51,
    total: 64,
    status: "published",
  },
  {
    id: "as2",
    title: "Sorting Algorithms Quiz",
    type: "quiz",
    dueDate: "Aug 2, 2026",
    points: 10,
    submitted: 60,
    total: 64,
    status: "closed",
  },
  {
    id: "as3",
    title: "Graph Traversal Lecture Notes",
    type: "material",
    dueDate: "—",
    points: 0,
    submitted: 0,
    total: 64,
    status: "published",
  },
  {
    id: "as4",
    title: "Dynamic Programming — Problem Set",
    type: "assignment",
    dueDate: "Aug 12, 2026",
    points: 25,
    submitted: 12,
    total: 64,
    status: "published",
  },
  {
    id: "as5",
    title: "Heaps & Priority Queues Quiz",
    type: "quiz",
    dueDate: "Aug 18, 2026",
    points: 15,
    submitted: 0,
    total: 64,
    status: "draft",
  },
];

export const announcements: AnnouncementItem[] = [
  {
    id: "an1",
    author: "Dr. Ananya Rao",
    avatar: "https://i.pravatar.cc/150?img=47",
    time: "2 hours ago",
    content:
      "Reminder: the practical exam covering graph traversal will be held next Monday in Lab 3. Please review BFS/DFS implementations beforehand.",
    comments: 6,
  },
  {
    id: "an2",
    author: "Dr. Ananya Rao",
    avatar: "https://i.pravatar.cc/150?img=47",
    time: "1 day ago",
    content:
      "Great work on the midterms, everyone! Detailed feedback has been attached to each submission. Office hours moved to Thursday 4–5 PM this week.",
    comments: 14,
  },
  {
    id: "an3",
    author: "Dr. Ananya Rao",
    avatar: "https://i.pravatar.cc/150?img=47",
    time: "3 days ago",
    content:
      "Assignment 3 has been posted under Classwork. It focuses on self-balancing trees — AVL and Red-Black. Due in two weeks.",
    comments: 3,
  },
];

export const weakTopics = [
  { topic: "Dynamic Programming", mastery: 42 },
  { topic: "Graph Algorithms", mastery: 55 },
  { topic: "Recursion & Backtracking", mastery: 61 },
  { topic: "Hashing", mastery: 68 },
];

export const assignmentDifficulty = [
  { name: "Lab 4 — BST", difficulty: 72 },
  { name: "Sorting Quiz", difficulty: 45 },
  { name: "DP Problem Set", difficulty: 88 },
  { name: "Heaps Quiz", difficulty: 58 },
];
